spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always           # Enable SQL initialization
      data-locations: classpath:data.sql
      platform: mariadb
      continue-on-error: true

  datasource:
    url: jdbc:mariadb://192.168.1.13:3306/mytestdb?createDatabaseIfNotExist=true
    username: root
    password: beowulf12
    driverClassName: org.mariadb.jdbc.Driver
    defer-datasource-initialization: true
  ai:
    mcp:
      server:
        stdio: false
        enabled: true
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message

logging:                                    # Fixed the logging structure
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework: INFO
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.ai.mcp: INFO

server:                                     # Fixed the server configuration structure
  port: 8890
